// <auto-generated />
using System;
using InventoryV2.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryV2.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20251129223012_AllInventoryTables")]
    partial class AllInventoryTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryV2.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("WorkingWarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("WorkingWarehouseId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("InventoryV2.Models.AuditableEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedIP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditableEntity");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InventoryV2.Models.Customer", b =>
                {
                    b.HasBaseType("InventoryV2.Models.AuditableEntity");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("InventoryV2.Models.Product", b =>
                {
                    b.HasBaseType("InventoryV2.Models.AuditableEntity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("InventoryV2.Models.RO_Product", b =>
                {
                    b.HasBaseType("InventoryV2.Models.AuditableEntity");

                    b.Property<int>("Product_Id")
                        .HasColumnType("int");

                    b.Property<double>("RO_Amount")
                        .HasColumnType("float");

                    b.Property<int>("RO_Id")
                        .HasColumnType("int");

                    b.Property<double>("RO_Price")
                        .HasColumnType("float");

                    b.Property<string>("RO_Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("Product_Id");

                    b.HasIndex("RO_Id");

                    b.ToTable("RO_Products");
                });

            modelBuilder.Entity("InventoryV2.Models.Release_Order", b =>
                {
                    b.HasBaseType("InventoryV2.Models.AuditableEntity");

                    b.Property<int>("Customer_ID")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("War_Number")
                        .HasColumnType("int");

                    b.HasIndex("Customer_ID")
                        .IsUnique()
                        .HasFilter("[Customer_ID] IS NOT NULL");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasFilter("[Number] IS NOT NULL");

                    b.HasIndex("War_Number");

                    b.ToTable("Release_Orders");
                });

            modelBuilder.Entity("InventoryV2.Models.SO_Product", b =>
                {
                    b.HasBaseType("InventoryV2.Models.AuditableEntity");

                    b.Property<int>("Product_Id")
                        .HasColumnType("int");

                    b.Property<double>("SO_Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("SO_EXP")
                        .HasColumnType("datetime2");

                    b.Property<int>("SO_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("SO_MFD")
                        .HasColumnType("datetime2");

                    b.Property<double>("SO_Price")
                        .HasColumnType("float");

                    b.Property<string>("SO_Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("Product_Id");

                    b.HasIndex("SO_Id");

                    b.ToTable("SO_Products");
                });

            modelBuilder.Entity("InventoryV2.Models.Supplier", b =>
                {
                    b.HasBaseType("InventoryV2.Models.AuditableEntity");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("InventoryV2.Models.Supply_Order", b =>
                {
                    b.HasBaseType("InventoryV2.Models.AuditableEntity");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Supplier_ID")
                        .HasColumnType("int");

                    b.Property<int>("War_Number")
                        .HasColumnType("int");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasFilter("[Number] IS NOT NULL");

                    b.HasIndex("Supplier_ID")
                        .IsUnique()
                        .HasFilter("[Supplier_ID] IS NOT NULL");

                    b.HasIndex("War_Number");

                    b.ToTable("Supply_Orders");
                });

            modelBuilder.Entity("InventoryV2.Models.TO_Product", b =>
                {
                    b.HasBaseType("InventoryV2.Models.AuditableEntity");

                    b.Property<int>("Product_Id")
                        .HasColumnType("int");

                    b.Property<double>("TO_Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("TO_EXP")
                        .HasColumnType("datetime2");

                    b.Property<int>("TO_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("TO_MFD")
                        .HasColumnType("datetime2");

                    b.Property<double>("TO_Price")
                        .HasColumnType("float");

                    b.Property<string>("TO_Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("Product_Id");

                    b.HasIndex("TO_Id");

                    b.ToTable("TO_Products");
                });

            modelBuilder.Entity("InventoryV2.Models.Transfer_Order", b =>
                {
                    b.HasBaseType("InventoryV2.Models.AuditableEntity");

                    b.Property<int>("From")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Supplier_ID")
                        .HasColumnType("int");

                    b.Property<int>("To")
                        .HasColumnType("int");

                    b.HasIndex("From");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasFilter("[Number] IS NOT NULL");

                    b.HasIndex("Supplier_ID");

                    b.HasIndex("To");

                    b.ToTable("Transfer_Orders");
                });

            modelBuilder.Entity("InventoryV2.Models.Warehouse", b =>
                {
                    b.HasBaseType("InventoryV2.Models.AuditableEntity");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManagerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("ManagerId")
                        .IsUnique()
                        .HasFilter("[ManagerId] IS NOT NULL");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasFilter("[Number] IS NOT NULL");

                    b.HasIndex("OwnerId");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("InventoryV2.Models.Warehouse_Product", b =>
                {
                    b.HasBaseType("InventoryV2.Models.AuditableEntity");

                    b.Property<DateTime>("EXP")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MFD")
                        .HasColumnType("datetime2");

                    b.Property<int>("Product_Id")
                        .HasColumnType("int");

                    b.Property<int>("Supplier_ID")
                        .HasColumnType("int");

                    b.Property<double>("Total_Amount")
                        .HasColumnType("float");

                    b.Property<double>("Total_Price")
                        .HasColumnType("float");

                    b.Property<int>("War_Id")
                        .HasColumnType("int");

                    b.HasIndex("Product_Id");

                    b.HasIndex("Supplier_ID");

                    b.HasIndex("War_Id");

                    b.ToTable("Warehouse_Products", (string)null);
                });

            modelBuilder.Entity("InventoryV2.Models.ApplicationUser", b =>
                {
                    b.HasOne("InventoryV2.Models.ApplicationUser", "SupervisedBy")
                        .WithMany("Subordinates")
                        .HasForeignKey("SupervisorId");

                    b.HasOne("InventoryV2.Models.Warehouse", "Working_Warehouse")
                        .WithMany("Employees")
                        .HasForeignKey("WorkingWarehouseId");

                    b.Navigation("SupervisedBy");

                    b.Navigation("Working_Warehouse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InventoryV2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InventoryV2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryV2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InventoryV2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryV2.Models.RO_Product", b =>
                {
                    b.HasOne("InventoryV2.Models.Product", "Product")
                        .WithMany("RO_Products")
                        .HasForeignKey("Product_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryV2.Models.Release_Order", "Release_Order")
                        .WithMany("RO_Products")
                        .HasForeignKey("RO_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Release_Order");
                });

            modelBuilder.Entity("InventoryV2.Models.Release_Order", b =>
                {
                    b.HasOne("InventoryV2.Models.Customer", "Customer")
                        .WithOne("Release_Order")
                        .HasForeignKey("InventoryV2.Models.Release_Order", "Customer_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryV2.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("War_Number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("InventoryV2.Models.SO_Product", b =>
                {
                    b.HasOne("InventoryV2.Models.Product", "Product")
                        .WithMany("SO_Products")
                        .HasForeignKey("Product_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryV2.Models.Supply_Order", "Supply_Order")
                        .WithMany("SO_Products")
                        .HasForeignKey("SO_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supply_Order");
                });

            modelBuilder.Entity("InventoryV2.Models.Supply_Order", b =>
                {
                    b.HasOne("InventoryV2.Models.Supplier", "Supplier")
                        .WithOne("Supply_Order")
                        .HasForeignKey("InventoryV2.Models.Supply_Order", "Supplier_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryV2.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("War_Number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("InventoryV2.Models.TO_Product", b =>
                {
                    b.HasOne("InventoryV2.Models.Product", "Product")
                        .WithMany("TO_Products")
                        .HasForeignKey("Product_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryV2.Models.Transfer_Order", "Transfer_Order")
                        .WithMany("TO_Products")
                        .HasForeignKey("TO_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Transfer_Order");
                });

            modelBuilder.Entity("InventoryV2.Models.Transfer_Order", b =>
                {
                    b.HasOne("InventoryV2.Models.Warehouse", "FromWarehouse")
                        .WithMany()
                        .HasForeignKey("From")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryV2.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("Supplier_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryV2.Models.Warehouse", "ToWarehouse")
                        .WithMany()
                        .HasForeignKey("To")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromWarehouse");

                    b.Navigation("Supplier");

                    b.Navigation("ToWarehouse");
                });

            modelBuilder.Entity("InventoryV2.Models.Warehouse", b =>
                {
                    b.HasOne("InventoryV2.Models.ApplicationUser", "Manager")
                        .WithMany("Managed_Warehouses")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryV2.Models.ApplicationUser", "Owner")
                        .WithMany("Owner_Warehouses")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("InventoryV2.Models.Warehouse_Product", b =>
                {
                    b.HasOne("InventoryV2.Models.AuditableEntity", null)
                        .WithOne()
                        .HasForeignKey("InventoryV2.Models.Warehouse_Product", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryV2.Models.Product", "Product")
                        .WithMany("Warehouse_Products")
                        .HasForeignKey("Product_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryV2.Models.Supplier", "Supplier")
                        .WithMany("Warehouse_Products")
                        .HasForeignKey("Supplier_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryV2.Models.Warehouse", "Warehouse")
                        .WithMany("Warehouse_Products")
                        .HasForeignKey("War_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("InventoryV2.Models.ApplicationUser", b =>
                {
                    b.Navigation("Managed_Warehouses");

                    b.Navigation("Owner_Warehouses");

                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("InventoryV2.Models.Customer", b =>
                {
                    b.Navigation("Release_Order")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryV2.Models.Product", b =>
                {
                    b.Navigation("RO_Products");

                    b.Navigation("SO_Products");

                    b.Navigation("TO_Products");

                    b.Navigation("Warehouse_Products");
                });

            modelBuilder.Entity("InventoryV2.Models.Release_Order", b =>
                {
                    b.Navigation("RO_Products");
                });

            modelBuilder.Entity("InventoryV2.Models.Supplier", b =>
                {
                    b.Navigation("Supply_Order")
                        .IsRequired();

                    b.Navigation("Warehouse_Products");
                });

            modelBuilder.Entity("InventoryV2.Models.Supply_Order", b =>
                {
                    b.Navigation("SO_Products");
                });

            modelBuilder.Entity("InventoryV2.Models.Transfer_Order", b =>
                {
                    b.Navigation("TO_Products");
                });

            modelBuilder.Entity("InventoryV2.Models.Warehouse", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Warehouse_Products");
                });
#pragma warning restore 612, 618
        }
    }
}
